### ISSUE TITLE
NeoVim Version Deprecated

### ISSUE THREAD

**Issue by jumin-lee** [Zachary-Lee-Jaeho/initial-settings#1]
NeoVim version is outdated, unmatching with NvChad and tsserver

Please check setup.sh and change to 
`89: wget https://github.com/neovim/neovim/releases/download/v0.10.1/nvim-linux64.tar.gz`

+ tsserver issue can be solved with changing "nvim-settings/lua/config/lspconfig.lua" to
`8: ts_ls`

Thank you for all

**Comment by Zachary-Lee-Jaeho** [comment]
Applied!
I upgrade neovim version to 0.10.1
and changed tsserver to ts_ls.
:)
